
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  type-test

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  defaultReadCapacityUnits:
    Type: Number
    Description: dynamodb Default ReadCapacityUnits
    Default: 2
  defaultWriteCapacityUnits:
    Type: Number
    Description: dynamodb Default WriteCapacityUnits
    Default: 2
  domainName:
    Type: String
    Description: domainName
    Default: domainName
  domainACM:
    Type: String
    Description: domainACM
    Default: domainACM

Resources:
  
  nestjsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name : nestjsApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type, Authorization, Content-Length, x-requested-with'"
        AllowOrigin: "'*'"
      Domain:
        DomainName: !Ref domainName
        CertificateArn: !Ref domainACM
        EndpointConfiguration: REGIONAL
        BasePath:
          - /

  nestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: dist/lambda.handler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 180
      Description: nestJS in dynamodb
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          DYNAMO_SCHOOL: !Ref schoolsTable
          DYNAMO_USER: !Ref usersTable
      Events:
        BackendApi:
          Type: Api
          Properties:
            RestApiId: !Ref nestjsApi
            Path: /{proxy+}
            Method: ANY

  schoolsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: area
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: area
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref defaultReadCapacityUnits
        WriteCapacityUnits: !Ref defaultWriteCapacityUnits

  usersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: role
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: role
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref defaultReadCapacityUnits
        WriteCapacityUnits: !Ref defaultWriteCapacityUnits

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${nestjsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"