
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  type-test

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  default_ReadCapacityUnits:
    Type: Number
    Description: dynamodb Default ReadCapacityUnits
    Default: 2
  default_WriteCapacityUnits:
    Type: Number
    Description: dynamodb Default WriteCapacityUnits
    Default: 2

Resources:

  nestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dist/lambda.handler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 180
      Description: nestJS in dynamodb
      # Policies:
        # - DynamoDBCrudPolicy:
        #     TableName: - !Ref schoolTable
        #       - !Ref userTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          DYNAMO_SCHOOL: !Ref schoolsTable
          DYNAMO_USER: !Ref usersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  schoolsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: area
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: area
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref default_ReadCapacityUnits
        WriteCapacityUnits: !Ref default_WriteCapacityUnits

  usersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: grade
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: grade
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref default_ReadCapacityUnits
        WriteCapacityUnits: !Ref default_WriteCapacityUnits

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"